# -*- coding: utf-8 -*-
"""spaceEda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QoQv7-9YVCg1CMHqf9fYV09Orn1g9UpB
"""

!pip install opencv-python matplotlib pandas

import pandas as pd
import matplotlib.pyplot as plt
import cv2
import os

from google.colab import drive
drive.mount('/content/drive')

data_dir = '/content/drive/MyDrive/Colab Notebooks/archive'
print("Files in directory:", os.listdir(data_dir))

images_dir = os.path.join(data_dir, 'train','images')
labels_dir = os.path.join(data_dir,  'train','labels')
print("no of img:", len(os.listdir(images_dir)))
print("No of labels:", len(os.listdir(labels_dir)))

sample_image = os.listdir(images_dir)[37]
img = cv2.imread(os.path.join(images_dir, sample_image))
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

sample_label = sample_image.replace('.jpg', '.txt')
with open(os.path.join(labels_dir, sample_label)) as f:
    labels = f.readlines()
print( labels)
# there are 11 classes with multiple objects type to

h, w = img.shape[:2]
for line in labels:
    cls, x, y, bw, bh = map(float, line.strip().split()) #since x is width y is height, un-normalize them and draw bounding boxes around objects
    xc, yc = int(x*w), int(y*h)
    box_w, box_h = int(bw*w), int(bh*h)
    x1, y1 = int(xc - box_w/2), int(yc - box_h/2)
    x2, y2 = int(xc + box_w/2), int(yc + box_h/2)
    img = cv2.rectangle(img, (x1, y1), (x2, y2), (0,255,0), 2)

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

import glob
label_files = glob.glob(os.path.join(labels_dir, '*.txt'))
class_counts = {}
for lbl_file in label_files:
    with open(lbl_file) as f:
        for line in f:
            cls = int(line.split()[0])
            class_counts[cls] = class_counts.get(cls, 0) + 1

print("classes:", class_counts)

